
development:
  adapter: postgresql
  encoding: unicode
  database: bamboo_development
  pool: 5
  host: localhost
  username: root

test:
  adapter: postgresql
  encoding: unicode
  database: bamboo_test
  pool: 5
  host: localhost
  username: root

production:
  adapter: postgresql
  encoding: unicode
  database: bamboo_production
  pool: 5
  username: <%= ENV['BAMBOO_DB_USERNAME'] %>
  password: <%= ENV['BAMBOO_DB_PASSWORD'] %>
