
development:
  adapter: postgresql
  encoding: unicode
  database: bamboo_development
  pool: 5
  username: root
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bamboo_test
  pool: 5
  username: root
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: bamboo_production
  pool: 5
  username: root
  password:
